// AUTO-GENERATED by scripts/calibrate-calendar-templates.ts — DO NOT EDIT BY HAND.
// Per-month grid geometry of the Revolución Z calendar PDF templates in calendar/.
// Coords are poppler bbox space: top-left origin, y grows DOWN, PDF points.
// Re-run `tsx scripts/calibrate-calendar-templates.ts` if the templates change.

import type { MonthTemplateGeometry } from './template-geometry.js';

export const TEMPLATE_GEOMETRY: Record<string, MonthTemplateGeometry> = {
  "2026-08": {
    "monthKey": "2026-08",
    "file": "Agosto 2026.pdf",
    "pageWidth": 1440,
    "pageHeight": 809.999993,
    "rowPitch": 80.56,
    "columns": [
      {
        "left": 122.5,
        "right": 303.5
      },
      {
        "left": 303.5,
        "right": 484.5
      },
      {
        "left": 484.5,
        "right": 666.5
      },
      {
        "left": 666.5,
        "right": 846
      },
      {
        "left": 846,
        "right": 1026.5
      },
      {
        "left": 1026.5,
        "right": 1206.5
      },
      {
        "left": 1206.5,
        "right": 1389
      }
    ],
    "rows": [
      {
        "numberTop": 262.19,
        "numberBottom": 288.77
      },
      {
        "numberTop": 343.76,
        "numberBottom": 370.34
      },
      {
        "numberTop": 423.53,
        "numberBottom": 450.12
      },
      {
        "numberTop": 504.1,
        "numberBottom": 530.68
      },
      {
        "numberTop": 583.08,
        "numberBottom": 609.66
      },
      {
        "numberTop": 663.64,
        "numberBottom": 690.23
      }
    ]
  },
  "2026-12": {
    "monthKey": "2026-12",
    "file": "Diciembre 2026.pdf",
    "pageWidth": 1440,
    "pageHeight": 809.999993,
    "rowPitch": 96.73,
    "columns": [
      {
        "left": 122.5,
        "right": 303.5
      },
      {
        "left": 303.5,
        "right": 484.5
      },
      {
        "left": 484.5,
        "right": 666.5
      },
      {
        "left": 666.5,
        "right": 846
      },
      {
        "left": 846,
        "right": 1026.5
      },
      {
        "left": 1026.5,
        "right": 1206.5
      },
      {
        "left": 1206.5,
        "right": 1389
      }
    ],
    "rows": [
      {
        "numberTop": 272.95,
        "numberBottom": 299.54
      },
      {
        "numberTop": 369.68,
        "numberBottom": 396.27
      },
      {
        "numberTop": 466.41,
        "numberBottom": 493
      },
      {
        "numberTop": 558.7,
        "numberBottom": 585.28
      },
      {
        "numberTop": 655.43,
        "numberBottom": 682.01
      }
    ]
  },
  "2026-07": {
    "monthKey": "2026-07",
    "file": "Julio 2026.pdf",
    "pageWidth": 1440,
    "pageHeight": 809.999993,
    "rowPitch": 96.7,
    "columns": [
      {
        "left": 122.5,
        "right": 303.5
      },
      {
        "left": 303.5,
        "right": 484.5
      },
      {
        "left": 484.5,
        "right": 666.5
      },
      {
        "left": 666.5,
        "right": 846
      },
      {
        "left": 846,
        "right": 1026.5
      },
      {
        "left": 1026.5,
        "right": 1206.5
      },
      {
        "left": 1206.5,
        "right": 1389
      }
    ],
    "rows": [
      {
        "numberTop": 273.01,
        "numberBottom": 299.59
      },
      {
        "numberTop": 369.71,
        "numberBottom": 396.29
      },
      {
        "numberTop": 466.42,
        "numberBottom": 492.99
      },
      {
        "numberTop": 558.68,
        "numberBottom": 585.25
      },
      {
        "numberTop": 655.38,
        "numberBottom": 681.96
      }
    ]
  },
  "2026-06": {
    "monthKey": "2026-06",
    "file": "Junio 2026.pdf",
    "pageWidth": 1440,
    "pageHeight": 809.999993,
    "rowPitch": 96.73,
    "columns": [
      {
        "left": 122.5,
        "right": 303.5
      },
      {
        "left": 303.5,
        "right": 484.5
      },
      {
        "left": 484.5,
        "right": 666.5
      },
      {
        "left": 666.5,
        "right": 846
      },
      {
        "left": 846,
        "right": 1026.5
      },
      {
        "left": 1026.5,
        "right": 1206.5
      },
      {
        "left": 1206.5,
        "right": 1389
      }
    ],
    "rows": [
      {
        "numberTop": 272.94,
        "numberBottom": 299.53
      },
      {
        "numberTop": 369.67,
        "numberBottom": 396.26
      },
      {
        "numberTop": 466.41,
        "numberBottom": 493
      },
      {
        "numberTop": 558.7,
        "numberBottom": 585.29
      },
      {
        "numberTop": 655.44,
        "numberBottom": 682.02
      }
    ]
  },
  "2026-11": {
    "monthKey": "2026-11",
    "file": "Noviembre 2026.pdf",
    "pageWidth": 1440,
    "pageHeight": 809.999993,
    "rowPitch": 78.21,
    "columns": [
      {
        "left": 122.5,
        "right": 303.5
      },
      {
        "left": 303.5,
        "right": 484.5
      },
      {
        "left": 484.5,
        "right": 666.5
      },
      {
        "left": 666.5,
        "right": 846
      },
      {
        "left": 846,
        "right": 1026.5
      },
      {
        "left": 1026.5,
        "right": 1206.5
      },
      {
        "left": 1206.5,
        "right": 1389
      }
    ],
    "rows": [
      {
        "numberTop": 273.71,
        "numberBottom": 300.3
      },
      {
        "numberTop": 352.14,
        "numberBottom": 378.73
      },
      {
        "numberTop": 430.35,
        "numberBottom": 456.94
      },
      {
        "numberTop": 511.64,
        "numberBottom": 538.23
      },
      {
        "numberTop": 589.85,
        "numberBottom": 616.44
      },
      {
        "numberTop": 668.07,
        "numberBottom": 694.66
      }
    ]
  },
  "2026-10": {
    "monthKey": "2026-10",
    "file": "Octubre 2026.pdf",
    "pageWidth": 1440,
    "pageHeight": 809.999993,
    "rowPitch": 96.72,
    "columns": [
      {
        "left": 122.5,
        "right": 303.5
      },
      {
        "left": 303.5,
        "right": 484.5
      },
      {
        "left": 484.5,
        "right": 666.5
      },
      {
        "left": 666.5,
        "right": 846
      },
      {
        "left": 846,
        "right": 1026.5
      },
      {
        "left": 1026.5,
        "right": 1206.5
      },
      {
        "left": 1206.5,
        "right": 1389
      }
    ],
    "rows": [
      {
        "numberTop": 279.88,
        "numberBottom": 306.47
      },
      {
        "numberTop": 376.6,
        "numberBottom": 403.19
      },
      {
        "numberTop": 473.32,
        "numberBottom": 499.9
      },
      {
        "numberTop": 565.6,
        "numberBottom": 592.18
      },
      {
        "numberTop": 662.32,
        "numberBottom": 688.9
      }
    ]
  },
  "2026-09": {
    "monthKey": "2026-09",
    "file": "Septiembre 2026.pdf",
    "pageWidth": 1440,
    "pageHeight": 809.999993,
    "rowPitch": 96.75,
    "columns": [
      {
        "left": 122.5,
        "right": 303.5
      },
      {
        "left": 303.5,
        "right": 484.5
      },
      {
        "left": 484.5,
        "right": 666.5
      },
      {
        "left": 666.5,
        "right": 846
      },
      {
        "left": 846,
        "right": 1026.5
      },
      {
        "left": 1026.5,
        "right": 1206.5
      },
      {
        "left": 1206.5,
        "right": 1389
      }
    ],
    "rows": [
      {
        "numberTop": 272.91,
        "numberBottom": 299.5
      },
      {
        "numberTop": 369.66,
        "numberBottom": 396.25
      },
      {
        "numberTop": 466.41,
        "numberBottom": 493
      },
      {
        "numberTop": 558.71,
        "numberBottom": 585.3
      },
      {
        "numberTop": 655.46,
        "numberBottom": 682.05
      }
    ]
  }
};
